# Задача 2

#num = input("Pls input 3 grade number: ")
#num = int(num)

#n1 = num % 10
#num = num // 10
#n2 = num % 10
#num = num // 10

#print(num + n1 + n2)


# Задача 4

#S = int(input())
#print(S//4, S//2, S//4)


# Задача 6

"""
n = input("Pls input 6 grade number: ")

s1 = int(n[0]) + int(n[1]) + int(n[2])
s2 = int(n[3]) + int(n[4]) + int(n[5])
if s1 == s2:
    print('lucky')
else:
    print('unlucky')
"""

# Задача 8

"""
n = int(input("pls input n: "))
m = int(input("pls input m: "))
k = int(input("pls input k: "))

if k < m * n and (k % m == 0 or k % n ==0 ):
    print('yes')
else:
    print('no')
"""


